apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "price-watch.fullname" . }}
  labels:
    {{- include "price-watch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi